# Generated by Django 4.2.4 on 2023-09-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_icon', models.CharField(max_length=50)),
                ('Service_title', models.CharField(max_length=50)),
                ('Service_des', models.TextField()),
            ],
        ),
    ]
